### ISSUE TITLE
Catch cloudflare exception & write it back to the user incase of rate limiting

### ISSUE THREAD

**Issue by OhhLoz** [OhhLoz/HLTVBot#56]

**Comment by OhhLoz** [comment]
// h:\Documents\Apps\HLTVBot\node_modules\hltv\lib\utils.js:78
//                     throw new Error('Access denied | www.hltv.org used Cloudflare to restrict access');
//                           ^

// Error: Access denied | www.hltv.org used Cloudflare to restrict access
//     at h:\Documents\Apps\HLTVBot\node_modules\hltv\lib\utils.js:78:27
//     at step (h:\Documents\Apps\HLTVBot\node_modules\hltv\lib\utils.js:56:23)
//     at Object.next (h:\Documents\Apps\HLTVBot\node_modules\hltv\lib\utils.js:37:53)
//     at fulfilled (h:\Documents\Apps\HLTVBot\node_modules\hltv\lib\utils.js:28:58)
//     at processTicksAndRejections (node:internal/process/task_queues:96:5)
