### ISSUE TITLE
/team stats teamname returns this error when teamdictionary is populated with the provided teamname but the teamstats table isnt

### ISSUE THREAD

**Issue by OhhLoz** [OhhLoz/HLTVBot#78]
TypeError: Cannot read properties of undefined (reading 'created_at')
    at h:\Documents\Apps\HLTVBot\node_modules\sequelize\lib\model.js:1616:39
    at Array.map (<anonymous>)
    at recursiveBulkCreate (h:\Documents\Apps\HLTVBot\node_modules\sequelize\lib\model.js:1614:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.bulkCreate (h:\Documents\Apps\HLTVBot\node_modules\sequelize\lib\model.js:1744:12)
    at async Object.queryHandler (h:\Documents\Apps\HLTVBot\databaseWrapper.js:86:22)

**Comment by OhhLoz** [comment]
Bug still present in 1.7.0, updated to urgent incase it causes further disruptions. Message is still displayed to the user but I believe the database isnt populated

**Comment by OhhLoz** [comment]
Downgraded from urgent as it doesnt affect population of the database as far as I can tell
